services:
  - name: backend
    type: web
    env: node
    plan: free
    buildCommand: cd server && npm install && npm run build  # ✅ Ensures TypeScript compiles
    startCommand: cd server && npm run start:prod  # ✅ Uses production start script
    envVars:
      - key: DATABASE_URL
        value: postgresql://zipzapdb_user:xDgi2K0OWQ2KgRQEq89dufZfrEY2LBaK@dpg-cvcmg53qf0us73di7rh0-a/zipzapdb  # Replace with your Render PostgreSQL Internal URL

  - name: frontend
    type: web
    env: node
    plan: free
    buildCommand: cd client && npm install && npm run build
    startCommand: cd client && npm install -g serve && serve -s out -l 3000
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://backend.onrender.com
