services:
  - name: postgres-db
    type: pserv
    env: docker
    plan: free
    dockerContext: .
    dockerfilePath: Dockerfile.db
    envVars:
      - key: POSTGRES_USER
        value: user
      - key: POSTGRES_PASSWORD
        value: password
      - key: POSTGRES_DB
        value: ayush
      - key: DATABASE_URL
        value: postgres://user:password@postgres-db:5432/ayush

  - name: backend
    type: web
    env: node
    plan: free
    buildCommand: npm install && npx prisma migrate deploy
    startCommand: npm run start
    envVars:
      - key: DATABASE_URL
        value: postgres://user:password@postgres-db:5432/ayush

  - name: frontend
    type: web
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm install -g serve && serve -s out -l 3000
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://backend.onrender.com
